version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/react-redux-aws-deploy
permissions:
- object: /home/ubuntu
  owner: ubuntu
  group: ubuntu
  type:
  - directory
  - file
hooks:
  ApplicationStop:
  - location: codeDeploy/stopApp.sh
    timeout: 60
    runas: ubuntu
  BeforeInstall:
  - location: codeDeploy/removeExistingVersion.sh
    timeout: 60
    runas: ubuntu
  - location: codeDeploy/install.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: codeDeploy/postInstall.sh
    timeout: 300
    runas: ubuntu
  ApplicationStart:
  - location: codeDeploy/startApp.sh
    timeout: 60
    runas: ubuntu
